#!/usr/bin/env python3
"""Re-apply the offline patches that keep vendored dependencies off the network.

`Vendor/` is generated by `prepare_dependencies.py` and is not tracked by git, so any
fresh checkout or dependency refresh restores upstream WhisperKit — which starts an
`NWPathMonitor` as soon as a `HubApi` is constructed and downloads the Whisper tokenizer
from huggingface.co when it is not found locally. Both behaviors break the rule that the
app never requires or requests a network connection, so they are patched out here and the
result is verified rather than assumed.
"""

from __future__ import annotations

import json
import pathlib
import shutil
import sys


def code_only(text: str) -> str:
    """Return source with line comments removed.

    The patched files explain in comments which network APIs were taken out, so the
    forbidden-pattern check must read code rather than prose.
    """
    return "\n".join(line.split("//", 1)[0] for line in text.splitlines())


def load_pinned_revision(project: pathlib.Path, dependency: str) -> str:
    """Return the revision a dependency is pinned to."""
    pins = json.loads((project / "Config" / "DependencyPins.json").read_text())
    return str(pins["dependencies"][dependency]["revision"])


def apply_patch(project: pathlib.Path, patch_directory: pathlib.Path) -> None:
    """Install patched sources over one vendored dependency and verify the result."""
    patch = json.loads((patch_directory / "offline-patch.json").read_text())
    dependency = str(patch["dependency"])
    pinned = load_pinned_revision(project, dependency)
    authored = str(patch["revision"])
    if pinned != authored:
        raise RuntimeError(
            f"{dependency} is pinned to {pinned} but the offline patch was authored for "
            f"{authored}. Re-author {patch_directory / 'offline-patch.json'} and its "
            f"stored sources against the new revision before building offline."
        )

    vendor = project / "Vendor" / dependency
    if not vendor.is_dir():
        raise RuntimeError(f"Vendored {dependency} is missing at {vendor}")

    marker = str(patch["requiredMarker"])
    for entry in patch["files"]:
        relative = str(entry["path"])
        source = patch_directory / relative
        destination = vendor / relative
        if not source.is_file():
            raise RuntimeError(f"Stored patch source is missing: {source}")
        if not destination.is_file():
            raise RuntimeError(f"Upstream file to patch is missing: {destination}")
        shutil.copyfile(source, destination)

        text = destination.read_text()
        if marker not in text:
            raise RuntimeError(f"Patched file lost its {marker} marker: {destination}")
        code = code_only(text)
        for forbidden in entry["forbidden"]:
            if forbidden in code:
                raise RuntimeError(
                    f"Offline patch failed: {destination} still contains {forbidden!r}"
                )
        print(f"Offline patch applied and verified: {dependency}/{relative}")


def main() -> int:
    """Apply every stored offline patch to its vendored dependency."""
    project = pathlib.Path(__file__).resolve().parents[1]
    patches_root = project / "Patches"
    if not patches_root.is_dir():
        raise RuntimeError(f"Patches directory is missing: {patches_root}")
    directories = sorted(path for path in patches_root.iterdir() if path.is_dir())
    if not directories:
        raise RuntimeError(f"No offline patches found under {patches_root}")
    for patch_directory in directories:
        apply_patch(project, patch_directory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
